# Question1

## Q.1 - Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.

In [26]:
import numpy as np
import sys
a=np.random.randint(0,100,(10,1))
print(a)
print("mean:-",a.mean())

[[91]
 [65]
 [11]
 [14]
 [89]
 [78]
 [77]
 [32]
 [30]
 [95]]
mean:- 58.2


## Question2


## Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.

In [23]:
import numpy as np
import sys
a=np.random.randint(0,100,(20,1))
print(a)
print("variance:-",a.var())
print("standard deviation:-",a.std())


[[50]
 [31]
 [19]
 [90]
 [85]
 [85]
 [77]
 [33]
 [98]
 [92]
 [51]
 [82]
 [11]
 [59]
 [90]
 [92]
 [58]
 [28]
 [33]
 [88]]
variance:- 777.74
standard deviation:- 27.887990246699385


## Question3


## Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.


In [21]:
import numpy as np
import sys
a=np.random.randint(0,100,(10,20))
print("matric A :-",a)
b=np.random.randint(0,100,(20,25))
print("\nmatric B:-",b)
c=np.matmul(a,b)
print("\nmatric A&B:-",c)
print("\n sum:-",c.sum())


matric A :- [[ 6 69 17 78 60 21 94 19 97  0 68 12 97 35 33 94 90 62 11 39]
 [26 32 83 16 54 24  1 88 16 73 70 39 53 50 87 81 28 68 38 98]
 [18 11 64 95 94 51 82  8 96  9 90 31 11 76 76  5  6 38 79 74]
 [78 60 46 70 98 65 36 24 61 70 11  7 88 15  7 76 76 96 80 72]
 [92 16 94 13 57 51 26 85 87 55 66 54 17 67 41 26 36 15 15 83]
 [ 2 47 45 97 66 63 55 59 70 46 93 34 92 66 68 55 88 96 11 25]
 [53 18 92 29 45 58 28  5  7 75 45 19 35 79  5 69 47 70 28 60]
 [51 67 81 18 35 77 99 91 28 74 42 68 88 82 94 63 63 55 78 78]
 [68 78 36 68 18 49 59  2 84  3 54 34 34 77 32 80 31 91 71 43]
 [14 55  6 31 40  8 52 29 21 63  0 90 34 83 80 20 16 74  5 32]]

matric B:- [[44 41 91  5 93 65 18 34 48 72 81 31 54 37 27 91 25 50 59 34 11 20 90 87
  60]
 [ 0 10 91 58 24 94 27 63 35 71 17 41 75  5 76 12 38  2 42 74 12  9 21 18
  19]
 [54 14 11 15 55 52 49 45 71 66 85  0 81 82 79 73 95 13 97 48 41 72 64 77
   4]
 [92 81 56 90 80  4  9 82  4 50 49 85 66 95 49 95 28 40 29 66 53 26 94 98
  52]
 [50 83 67 14 22 33 50 43

## Question4

## Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. 

## f(x)=1 / (1 + exp(-x)) 
## Apply this function to each element of A and print the new array holding the value the function returns
## Example:

 ## a=[a1,a2,a3]   
## n(new array to be printed )=[ f(a1), f(a2), f(a3)]


In [24]:
import numpy as np
import sys
def fun(a):
    return(1/1+np.exp(-a))
a=np.random.randint(0,100,(10,1))
print(a)
b=[]
for i in a:
    x=fun(i)
    b.append(x)
    
print(np.array(b))

[[85]
 [67]
 [33]
 [99]
 [31]
 [53]
 [61]
 [40]
 [18]
 [21]]
[[1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.00000002]
 [1.        ]]
